# Generated by Django 5.1.6 on 2025-02-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Текстовые данные'},
        ),
    ]
